import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Metamask info dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <h1>Moralis info dashboard</h1>
        <Link href="/login" className="button">
          Get Started
        </Link>
      </main>
    </div>
  );
}
