import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Metamask Moralis Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Simple NextAuth,Metamask Moralis Login</h1>
        <Link href="/signin" className={styles.button}>
          Signin
        </Link>
      </main>
    </div>
  );
}
